export enum PetTypeEnum {
  DOG = 'dog',
  CAT = 'cat',
  RABBIT = 'rabbit',
  HAMSTER = 'hamster',
  FERRET = 'ferret',
  PARROT = 'parrot',
  CHIKEN = 'chiken',
  GOOSE = 'goose',
  TURKEY = 'turkey',
  GUINEA_PIG = 'guinea pig',
  COW = 'cow',
  HORSE = 'horse',
  DONKEY = 'donkey',
  CAMEL = 'camel',
  PIG = 'pig',
  SHEEP = 'sheep',
  GOAT = 'goat',
  SNAKE = 'snake',
  LIZARD = 'lizard',
  TURTLE = 'turtle',
}
